# Generated by Django 2.1.4 on 2019-04-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
