# Generated by Django 2.1.4 on 2019-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('limit', models.IntegerField(default=200)),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束')], default=0)),
                ('address', models.CharField(max_length=50)),
                ('times', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('e_mail', models.EmailField(max_length=30, null=True, unique=True)),
                ('event', models.ManyToManyField(to='api.Event')),
            ],
        ),
    ]
